### ISSUE TITLE
pulse counter problem

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/raspimouse2#10]
Due to instabilities in either the hardware pulse counters or the kernel driver for them, it is
  possible for reading from the pulse counters to cause the node to freeze. If this happens
  regularly, disable the hardware pulse counters using the `use_pulse_counters` parameter and
  rely on estimated odometry instead.

**Comment by Tiryoh** [comment]
related issue: https://github.com/rt-net/RaspberryPiMouse/issues/13

This problem is not caused by this ROS2 package.
Add the following line to `/boot/firmware/config.txt` to fix the baudrate of I2C on Raspberry Pi.

```
dtparam=i2c_baudrate=62500
```
