### ISSUE TITLE
https://rt-net.jp/mobility/archives/13403  におけるエラーについて

### ISSUE THREAD

**Issue by ghost** [rt-net/raspimouse2#31]
# 不具合の概要
 ラズパイマウスのROS 2パッケージをインストールする　
 https://rt-net.jp/mobility/archives/13403 
 を参考にラズパイマウスV3のテストを行っております。
 # Clone package　の部分で記述どおりに、
 git clone https://github.com/rt-net/raspimouse2
 を実行しますと、そのあとの
 rosdep install -r -y -i --from-paths .
 を実行しますと以下のエラーが出てしまい先に進むことができずにおります。

# 実行環境
 RaspberryPi3
 Ubuntu18.04

# ログ・画像
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.

---
Failed   <<< raspimouse_msgs [7.49s, exited with code 1]

Summary: 0 packages finished [8.64s]
  1 package failed: raspimouse_msgs
  1 package had stderr output: raspimouse_msgs
  1 package not processed

**Comment by ShotaAk** [comment]
ROS 2パッケージが１つも見つかっていないようです。
rosdepコマンドの実行前にセットアップスクリプトを読み込んで下さい。

```bash
$ source /opt/ros/dashing/setup.bash
$ rosdep install -r -y -i --from-paths .
```

**Comment by ghost** [comment]
ご教授ありがとうございます
ubuntu@ubuntu:~$ source /opt/ros/dashing/setup.bash
ubuntu@ubuntu:~$ rosdep install -r -y -i --from-paths .
#All required rosdeps installed successfully
となるのですが、ウェブサイトの手順通りに、再度進めましても、
ubuntu@ubuntu:~$ source ~/ros2_ws/install/setup.bash
ubuntu@ubuntu:~$ ros2 run raspimouse raspimouse
Package 'raspimouse' not found
となってしまうのです。

ディレクトリは子の様になっております
ubuntu@ubuntu:~$ ls
Desktop    Downloads  Pictures  RaspberryPiMouse  ros2_ws2   Videos
Documents  Music      Public    ros2_ws           Templates

ウェブサイトの手順の最初にもどりまして、
ubuntu@ubuntu:~$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$
ubuntu@ubuntu:~/ros2_ws$ colcon build

Summary: 0 packages finished [1.34s]
となり、

ubuntu@ubuntu:~/ros2_ws$ ls
build  install  log  raspimouse2  src
というディレクトリがちゃんと作成されております。

次の手順の
ubuntu@ubuntu:~/ros2_ws$ cd ~/ros2_ws/src
ubuntu@ubuntu:~/ros2_ws/src$ git clone https://github.com/rt-net/raspimouse2
が間違っているのでしょうか？

foxyではなくdashingですので、
git clone -b dashing-devel https://github.com/rt-net/raspimouse2
を実行すべきなのでしょうか？？

**Comment by ghost** [comment]
> ROS 2パッケージが１つも見つかっていないようです。
> rosdepコマンドの実行前にセットアップスクリプトを読み込んで下さい。
> 
> ```shell
> $ source /opt/ros/dashing/setup.bash
> $ rosdep install -r -y -i --from-paths .
> ```

ラズパイマウスV3を一度シャットダウンし、
頂きました上記コマンドを再度実行すると下記のようなエラーが出るようになりました。
もう訳がわからず途方にくれております。

ubuntu@ubuntu:~$ source /opt/ros/dashing/setup.bash
ubuntu@ubuntu:~$ rosdep install -r -y -i --from-paths .

ERROR: Rosdep experienced an error: Multiple packages found with the same name "raspimouse":
- ros2_ws/src/raspimouse2/raspimouse
- ros2_ws2/src/raspimouse2/raspimouse
Multiple packages found with the same name "raspimouse_msgs":
- ros2_ws/src/raspimouse2/raspimouse_msgs
- ros2_ws2/src/raspimouse2/raspimouse_msgs
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.8

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 137, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 383, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 436, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 96, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "raspimouse":
- ros2_ws/src/raspimouse2/raspimouse
- ros2_ws2/src/raspimouse2/raspimouse
Multiple packages found with the same name "raspimouse_msgs":
- ros2_ws/src/raspimouse2/raspimouse_msgs
- ros2_ws2/src/raspimouse2/raspimouse_msgs

**Comment by ShotaAk** [comment]
こちらについては、`ros2_ws`、`ros2_ws2`の2つ環境に同じパッケージを用意し、その両方のワークスペースをsourceしていることが原因です。

#32 においてビルドまで進んでいるため、このissueはクローズします。
