### ISSUE TITLE
https://rt-net.jp/mobility/archives/13403 におけるエラーについて　その２

### ISSUE THREAD

**Issue by ghost** [rt-net/raspimouse2#32]
# 不具合の概要
 ラズパイマウスのROS 2パッケージをインストールする　
 https://rt-net.jp/mobility/archives/13403 
 を参考にラズパイマウスV3のテストを行っております。

 # Build & Install　の部分で記述どおりに、
  $ cd ~/ros2_ws
  $ colcon build --symlink-install
 を実行しますと、以下のエラーが出てしまい先に進むことができずにおります。

# 実行環境
 RaspberryPi3
 Ubuntu18.04

# ログ・画像
ubuntu@ubuntu:~/ros2_ws/src$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
---
Failed   <<< raspimouse_msgs [0.84s, exited with code 1]

Summary: 0 packages finished [2.30s]
  1 package failed: raspimouse_msgs
  1 package had stderr output: raspimouse_msgs
  1 package not processed

**Comment by ShotaAk** [comment]
ROS 2 Dashing環境では`dashing-devel`ブランチに切り替えてビルドしてみて下さい。

```sh
$ cd ~/ros2_ws/src/raspimouse2
$ git checkout dashing-devel
$ cd ~/ros2_ws
$ colcon build --symlink-install
```

**Comment by ghost** [comment]
> ROS 2 Dashing環境では`dashing-devel`ブランチに切り替えてビルドしてみて下さい。
> 
> ```shell
> $ cd ~/ros2_ws/src/raspimouse2
> $ git checkout dashing-devel
> $ cd ~/ros2_ws
> $ colcon build --symlink-install
> ```

ありがとうございます。早速試してみたのですが、以下の様に同じエラーとなってしまいます。

ubuntu@ubuntu:~$  cd ~/ros2_ws/src/raspimouse2
ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ git checkout dashing-devel
Branch 'dashing-devel' set up to track remote branch 'dashing-devel' from 'origin'.
Switched to a new branch 'dashing-devel'
ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
---
Failed   <<< raspimouse_msgs [0.79s, exited with code 1]

Summary: 0 packages finished [2.33s]
  1 package failed: raspimouse_msgs
  1 package had stderr output: raspimouse_msgs
  1 package not processed

**Comment by ShotaAk** [comment]
```
ubuntu@ubuntu:$ cd /ros2_ws/src/raspimouse2
ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ git checkout dashing-devel
Branch 'dashing-devel' set up to track remote branch 'dashing-devel' from 'origin'.
Switched to a new branch 'dashing-devel'
ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ cd /ros2_ws
ubuntu@ubuntu:/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.
```

`/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt` と表示されているので、
`ros2_ws`ディレクトリ直下に`raspimouse2`ディレクトリがあるようです。

こちらを削除してみて下さい。

**Comment by ghost** [comment]
> ```
> ubuntu@ubuntu:$ cd /ros2_ws/src/raspimouse2
> ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ git checkout dashing-devel
> Branch 'dashing-devel' set up to track remote branch 'dashing-devel' from 'origin'.
> Switched to a new branch 'dashing-devel'
> ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ cd /ros2_ws
> ubuntu@ubuntu:/ros2_ws$ colcon build --symlink-install
> Starting >>> raspimouse_msgs
> --- stderr: raspimouse_msgs
> CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.
> ```
> 
> `/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt` と表示されているので、
> `ros2_ws`ディレクトリ直下に`raspimouse2`ディレクトリがあるようです。
> 
> こちらを削除してみて下さい。


アールティ社のROS1サンプルと書籍のみで勉強しておるのですが、
普通にlinuxコマンドで消してしまってよいのでしょうか？
ROS2ではcatkinのかわりにcolconというのを使うと理解しており、colcon list を試しましたらこの様になっております。

ubuntu@ubuntu:~$ colcon list
raspimouse      ros2_ws/src/raspimouse2/raspimouse      (ros.ament_cmake)
raspimouse      ros2_ws2/src/raspimouse2/raspimouse     (ros.ament_cmake)
raspimouse_msgs ros2_ws/src/raspimouse2/raspimouse_msgs (ros.ament_cmake)
raspimouse_msgs ros2_ws2/src/raspimouse2/raspimouse_msgs        (ros.ament_cmake)

**Comment by ghost** [comment]
> ```
> ubuntu@ubuntu:$ cd /ros2_ws/src/raspimouse2
> ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ git checkout dashing-devel
> Branch 'dashing-devel' set up to track remote branch 'dashing-devel' from 'origin'.
> Switched to a new branch 'dashing-devel'
> ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ cd /ros2_ws
> ubuntu@ubuntu:/ros2_ws$ colcon build --symlink-install
> Starting >>> raspimouse_msgs
> --- stderr: raspimouse_msgs
> CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.
> ```
> 
> `/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt` と表示されているので、
> `ros2_ws`ディレクトリ直下に`raspimouse2`ディレクトリがあるようです。
> 
> こちらを削除してみて下さい。


度々恐縮です。このようになりました。
ubuntu@ubuntu:~/ros2_ws$ ls
build  install  log  raspimouse2  src
ubuntu@ubuntu:~/ros2_ws$ sudo rm -R raspimouse2
ubuntu@ubuntu:~/ros2_ws$ ls
build  install  log  src
ubuntu@ubuntu:~/ros2_ws$ cd ~/ros2_ws/src/raspimouse2
ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ git checkout dashing-devel
Already on 'dashing-devel'
Your branch is up to date with 'origin/dashing-devel'.
ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
---
Failed   <<< raspimouse_msgs [0.44s, exited with code 1]

Summary: 0 packages finished [1.59s]
  1 package failed: raspimouse_msgs
  1 package had stderr output: raspimouse_msgs
  1 package not processed

ラズパイマウスV3を分解して microSDにUbuntuいれるところからやり直した方がよいのでしょうか？・・・

**Comment by ghost** [comment]
一歩あともどりしてみようと思い、ひとつ前の記事
Raspberry Pi 4 にROS 2をインストールする
https://rt-net.jp/mobility/archives/13190
の最後「サンプルパッケージを実行する」を試してみたところ、
TalkerからListenerにメッセージが渡されております。

**Comment by ShotaAk** [comment]
```
ubuntu@ubuntu:~$ colcon list
raspimouse ros2_ws/src/raspimouse2/raspimouse (ros.ament_cmake)
raspimouse ros2_ws2/src/raspimouse2/raspimouse (ros.ament_cmake)
raspimouse_msgs ros2_ws/src/raspimouse2/raspimouse_msgs (ros.ament_cmake)
raspimouse_msgs ros2_ws2/src/raspimouse2/raspimouse_msgs (ros.ament_cmake)
```
上記より、`ros2_ws`と`ros2_ws2`の2つのワークスペースで作業していることがわかります。
ワークスペース内でビルドしたパッケージは、`source install/setup.bash`を実行することで読み込まれます。

まず、**`ros2_ws`、`ros2_ws2`のどちらを使うのか決めて下さい**。
そして、**そのワークスペースの`setup.bash`のみを読み込んで下さい**。

すでにsetup.bashを読み込んでいる場合は、ターミナルを立ち上げなおしてください。

> ラズパイマウスV3を分解して microSDにUbuntuいれるところからやり直した方がよいのでしょうか？・・・

ハードウェアに異常はないため、Ubuntuの再インストールは不要です。

**Comment by ShotaAk** [comment]
細かく書くと次のようなステップです。

1. ターミナルを起動する
2. ROS 2環境を読み込む `$ source /opt/ros/dashing/setup.bash`
3. 作業ワークスペースに移動する `$ cd ~/ros2_ws`
4. パッケージをビルドする `$ colcon build --symlink-install`

ビルドが成功したら
5. パッケージを読み込む `$ source install/setup.bash`

ビルドが失敗したら
5. エラーログを読み、原因を調査する

**Comment by ShotaAk** [comment]
```
ubuntu@ubuntu:/ros2_ws$ ls
build install log raspimouse2 src
ubuntu@ubuntu:/ros2_ws$ sudo rm -R raspimouse2
ubuntu@ubuntu:/ros2_ws$ ls
build install log src
ubuntu@ubuntu:/ros2_ws$ cd /ros2_ws/src/raspimouse2
ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ git checkout dashing-devel
Already on 'dashing-devel'
Your branch is up to date with 'origin/dashing-devel'.
ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ cd /ros2_ws
ubuntu@ubuntu:/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
--- stderr: raspimouse_msgs
CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.
```

上記より、`sudo rm -R raspimouse2`を実行しても、
一度ビルドしたキャッシュが残っているためエラーメッセージが表示されていることがわかります。

同じエラーメッセージが再発する場合は、`build`、`install`、`log`ディレクトリを削除した後にターミナルを立ち上げ直し、
ビルド作業を進めてみて下さい。

**Comment by ghost** [comment]
> ```
> ubuntu@ubuntu:/ros2_ws$ ls
> build install log raspimouse2 src
> ubuntu@ubuntu:/ros2_ws$ sudo rm -R raspimouse2
> ubuntu@ubuntu:/ros2_ws$ ls
> build install log src
> ubuntu@ubuntu:/ros2_ws$ cd /ros2_ws/src/raspimouse2
> ubuntu@ubuntu:/ros2_ws/src/raspimouse2$ git checkout dashing-devel
> Already on 'dashing-devel'
> Your branch is up to date with 'origin/dashing-devel'.
> ubuntu@ubuntu:~/ros2_ws/src/raspimouse2$ cd /ros2_ws
> ubuntu@ubuntu:/ros2_ws$ colcon build --symlink-install
> Starting >>> raspimouse_msgs
> --- stderr: raspimouse_msgs
> CMake Error: The source "/home/ubuntu/ros2_ws/src/raspimouse2/raspimouse_msgs/CMakeLists.txt" does not match the source "/home/ubuntu/ros2_ws/raspimouse2/raspimouse_msgs/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.
> ```
> 
> 上記より、`sudo rm -R raspimouse2`を実行しても、
> 一度ビルドしたキャッシュが残っているためエラーメッセージが表示されていることがわかります。
> 
> 同じエラーメッセージが再発する場合は、`build`、`install`、`log`ディレクトリを削除した後にターミナルを立ち上げ直し、
> ビルド作業を進めてみて下さい。

通りました！
そしてウェブサイト記述のブザーを鳴らす/止めるも動作確認しました！
本当にありがとうございます。

ubuntu@ubuntu:~/ros2_ws$ ls
build  install  log  src
ubuntu@ubuntu:~/ros2_ws$ sudo rm -R build
ubuntu@ubuntu:~/ros2_ws$ sudo rm -R install
ubuntu@ubuntu:~/ros2_ws$ sudo rm -R log
ubuntu@ubuntu:~/ros2_ws$ ls
src
ubuntu@ubuntu:~/ros2_ws$ cd ..
ubuntu@ubuntu:~$ ls
build    Documents  install  Music     Public            ros2_ws    Videos
Desktop  Downloads  log      Pictures  RaspberryPiMouse  Templates
ubuntu@ubuntu:~$ source /opt/ros/dashing/setup.bash
ubuntu@ubuntu:~$ cd ~/ros2_ws
ubuntu@ubuntu:~/ros2_ws$ colcon build --symlink-install
Starting >>> raspimouse_msgs
[Processing: raspimouse_msgs]
[Processing: raspimouse_msgs]
Finished <<< raspimouse_msgs [1min 11s]
Starting >>> raspimouse
[Processing: raspimouse]
[Processing: raspimouse]
Finished <<< raspimouse [1min 24s]

Summary: 2 packages finished [2min 36s]

**Comment by ghost** [comment]
復習のため
https://rt-net.jp/mobility/archives/13403
を最初からやり直したい場合は、build , install ,log を削除。

raspimouse2パッケージをクローンする手順はウェブサイトのまま、
　# Clone package
　$ cd ~/ros2_ws/src
　$ git clone https://github.com/rt-net/raspimouse2
で実行し、あとから、

$ cd ~/ros2_ws/src/raspimouse2
$ git checkout dashing-devel
で dashing に設定変更

$ cd ~/ros2_ws
$ colcon build --symlink-install
を実行して、

source ~/ros2_ws/install/setup.bash
がエラー無く終わればOKなのですね？

あとエラーメッセージをよく読みなさい。
そしてグーグルで調べなさい。ですね。

**Comment by ShotaAk** [comment]
@koshiba2020 無事にビルドできてよかったです :+1: 

今回、ブランチを切り替えるという手順が抜けていたため、
#33 にてパッケージのREADMEを更新します。
（ブログの記事にも手順を追記する予定です。）

ご報告ありがとうございました。

パッケージの動作に関して、
エラーメッセージから調査しても解決しない場合は、またIssueに投稿して頂いても構いません。

Issueを書くことによって（koshiba2020さんの投稿によって）、
このIssueが、同じエラーに直面した他のユーザの手助けになります。 :smile:
