### ISSUE TITLE
wheel_diameter、wheel_base、PULSES_PER_REVOLUTIONのROSパラメータ化

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/raspimouse2#34]
# 現状の問題点

このパッケージをラズパイマウス以外のロボットに流用する際に、
タイヤ直径とホイールベース、タイヤ一回転あたりのパルス数の違いが発生し、オドメトリを正しく計算できない問題が発生する。

https://github.com/rt-net/raspimouse2/blob/d9df35aa8d9bb2639469150d66e5f8a691ba3927/raspimouse/src/raspimouse_component.cpp#L36-L38

# 改善案

wheel_diameter、wheel_base、PULSES_PER_REVOLUTIONをROS パラメータ化する。

# その他

odometry_scale_right_wheel、odometry_scale_left_wheelはそのまま残しておく。

**Comment by shu-13** [comment]
以下のコミットで、wheel_diameterとwheel_baseをパラメータ化しました。  
use_pulse_counters_paramなどを参考にしてます
36976cf  

`raspimouse_ros2_examples`パッケージにある、`config/mouse.yml`に以下の2行を追加して、パラメータ調整が可能です。
```yml
wheel_diameter : 0.048
wheel_base : 0.09
```

PULSES_PER_REVOLUTIONの方は、以下の部分で使われています
https://github.com/rt-net/raspimouse2/blob/36976cf57b50c7f1bca72b2234983d783ae522ce/raspimouse/src/raspimouse_component.cpp#L517

その関係で、先の2つのパラメータと同じようにdouble型で取り込むと、ビルド時に以下のようなエラーが出ます。
```sh
/home/shu-rt/ros2_ws/src/raspimouse2/raspimouse/src/raspimouse_component.cpp: In member function ‘void raspimouse::Raspimouse::calculate_odometry_from_pulse_counts(double&, double&, double&)’:
/home/shu-rt/ros2_ws/src/raspimouse2/raspimouse/src/raspimouse_component.cpp:495:102: error: call to non-‘constexpr’ function ‘decltype(auto) rclcpp::Parameter::get_value() const [with T = double]’
  495 | LUTION = get_parameter(PULSES_PER_REVOLUTION_PARAM).get_value<double>();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```
対処方法については考え中です…

**Comment by shu-13** [comment]
以下のコミットで、PULSES_PER_REVOLUTIONもパラメータ化しました。
c401e5a


パラメータ化の手順は、wheel_diameterとwheel_baseと同等の方法で行いました。  
追加で、以下のconstexprで書かれていた部分をconstとして扱うようにしました。
https://github.com/rt-net/raspimouse2/blob/c401e5a0e0f4ac1eae9c083f80ba837c0dc00504/raspimouse/src/raspimouse_component.cpp#L517
