### ISSUE TITLE
rt-net/raspimouse2パッケージのインストールでfatalが発生する

### ISSUE THREAD

**Issue by ghost** [rt-net/raspimouse2#40]
# 不具合の概要
rt-net/raspimouse2パッケージのインストールでfatalが発生する

$ cd ~/ros2_ws/src

$ ~/ros2_ws/src$ git clone -b $ROS_DISTRO-devel https://github.com/rt-net/raspimouse2

Cloning into 'raspimouse2'...

fatal: Remote branch -devel not found in upstream origin

# 実行環境
- OS:Ubuntu 18.04>

これまでは正常に処理できていました。
どなたかお助けください。

**Comment by ShotaAk** [comment]
環境変数`$ROS_DISTRO`がセットされているか確認してください。

```sh
$ echo $ROS_DISTRO
dashing
```

セットされていない場合は、`$ source /opt/ros/dashing/setup.bash`を実行してください。

**Comment by ghost** [comment]
ありがとうございます。無事に処理できました。
